openapi: 3.0.0
info:
  title: 'ikuradon-salmon'
  description: 'Ikuradon Push Server Rest API'
  version: 2.0.0
paths:
  /health-check:
    get:
      summary: 'Health Check'
      responses:
        '200':
          description: Response
          content:
            application/json:
              schema:
                properties:
                  result:
                    type: boolean
                    description: 'always `true`.'
                    example: true
                  data:
                    properties:
                      name:
                        type: string
                        description: 'APP Name'
                        example: 'ikuradon-salmon'
                      version:
                        type: string
                        description: 'App Version'
                        example: '1.0.0'
  /api/v1/id:
    get:
      summary: ''
      security:
      - bearerAuth: []
      responses:
        '200':
          description: Response
          content:            
            application/json:
              schema:
                properties:
                  result:
                    type: boolean
                    description: 'always `true`.'
                    example: true
                  data:
                    properties:
                      subscribe_id:
                        type: string
                        description: 'Subscription ID'
                        example: '5f20f41b-d682-4592-b3bb-0b176ad9d075'
                      exponent_push_token:
                        type: string
                        description: 'Expo Push Token'
                        example: 'ExponentPushToken[xxxxxxxxxxxxxxxxxxxx]'
                      push_private_key:
                        type: string
                        description: 'Private Key'
                      push_auth:
                        type: string
                        description: 'Auth Common Key'
                      server_key:
                        type: string
                        description: 'Push Server Key'
                      created_at:
                        type: number
                        description: 'Created UNIXTIME'
                        example: 1591636409
                      last_updated_at:
                        type: number
                        description: 'Last Updated UNIXTIME'
                        example: 1591636409
        '401':
          description: 'Unauthorized - invailed subscribe_id'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error_response_body'
        '404':
          description: 'NotFound - Not subscibed ID'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error_response_body'
        '500':
          description: 'Internal Server Error'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error_response_body'
  /api/v2/subscribe:
    post:
      summary: 'Subscribe to push notifications.'
      parameters:
        -
          name: subscribe_id
          in: query
          description: 'Subscribe ID (recommend UUID-v4)'
          required: true
          schema:
            type: string
          example: '5f20f41b-d682-4592-b3bb-0b176ad9d075'
        -
          name: push_private_key
          in: query
          description: 'WebPush VAPIDPrivateKey'
          required: true
          schema:
            type: string
          example: 'VAPIDPrivateKey'
        -
          name: push_auth
          in: query
          description: 'Auth Secret Key'
          required: true
          schema:
            type: string
          example: 'AuthSecretKey'
        -
          name: server_key
          in: query
          description: 'SNS Server Key'
          required: true
          schema:
            type: string
          example: 'SNSServerKey'
        -
          name: exponent_push_token
          in: query
          description: 'ExponentPushToken'
          required: true
          schema:
            type: string
          example: 'ExponentPushToken[xxxxxxxxxxxxxxxxxxxx]'
      responses:
        '200':
          description: Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/result_response_body'
        '400':
          description: 'Bad Request'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error_response_body'
        '500':
          description: 'Internal Server Error'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error_response_body'
        '503':
          description: 'Dest Server Unavailable'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error_response_body'
  /api/v2/unsubscribe:
    post:
      summary: 'UnSubscribe to push notifications.'
      parameters:
        -
          name: subscribe_id
          in: query
          description: 'Subscribe ID (recommend UUID-v4)'
          required: true
          schema:
            type: string
          example: '5f20f41b-d682-4592-b3bb-0b176ad9d075'
      responses:
        '200':
          description: Response
          content:            
            application/json:
              schema:
                $ref: '#/components/schemas/result_response_body'
        '401':
          description: 'Unauthorized - invailed subscribe_id'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error_response_body'
        '404':
          description: 'NotFound - Not subscibed ID'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error_response_body'
        '500':
          description: 'Internal Server Error'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error_response_body'
components:
  schemas:
    error_response_body:
      properties:
        result:
          description: 'Always `false`.'
          type: boolean
          example: false
        errors:
          properties:
            code:
              description: 'Error Code'
              type: string
            message:
              description: 'Error Message'
              type: string
          type: object
      type: object
    result_response_body:
      properties:
        result:
          type: boolean
          example: true
        data:
          properties:
            subscribe_id:
              type: string
              nullable: true
              description: '64 characters'
              example: 'PbnWzSoSP1WBPXYbBsFgZWAj3lmZ23Ljr6i6b9HVIQZiTIthZqKsDbArEPnkJQOk'
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      description: "Use subscribe_id"
    